#%RAML 1.0 Library
types:
  orders:
    type: array
    items: order
  order:
    type: object
    properties:
      Order_Number__c?: string
      Gender__c?: string
      Product__c?: string
      Id?: string
      Id__c?: string
      type?: string
      Phone_Number__c?: string
      Name?: string
      Email__c?: string 
      Address__c?: string
      Payment_mode__c?: string
      Quantity__c?: string
